pipeline {
    agent any

    stages {
        stage('github Clone') {
            steps {
               git credentialsId: 'cloush24', url: 'https://github.com/Sanghyun124/AI_Convergence_Reservation_Program.git'
            }
        }
    }
}
