spring:
  profiles:
    active:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://3.36.79.129:3306/reservation_system?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: changhoon
    password: Css!2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: reservemailsender@gmail.com
    password: mvfgrftvtukkucov
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
