spring:
  profiles:
    active:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://3.34.10.4:3306/reservation_system?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: sanghyun
    password: Css!2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher
